---
- name: Check if loading kernel modules is possible
  ansible.builtin.command: "modprobe dummy"
  register: modprobe_test
  ignore_errors: true
  changed_when: false

- name: Fail when kernel module loading isn't possible
  ansible.builtin.fail:
    msg: "Kernel module loading isn't possible"
  when: modprobe_test.rc != 0
  changed_when: false

- name: Unload test kernel module
  ansible.builtin.command: "rmmod dummy"
  changed_when: false

- name: Check if systemd-modules-load can be used
  ansible.builtin.stat:
    path: "/etc/modules-load.d/"
  register: s

- name: Use modprobe.d for non-systemd servers
  ansible.builtin.set_fact:
    kernel_use_systemd_modules_load: false
    kernel_modules_conf_dir: "/etc/modprobe.d"
  when: not s.stat.exists

- ansible.builtin.include_tasks:
    file: blacklist-modules.yml

- ansible.builtin.include_tasks:
    file: unload-modules.yml

- ansible.builtin.include_tasks:
    file: load-modules.yml
