---
- name: Check if loading kernel modules is possible
  ansible.builtin.command: "modprobe dummy"
  register: modprobe_test
  ignore_errors: true
  changed_when: false

- name: Fail when kernel module loading isn't possible
  fail:
    msg: "Kernel module loading isn't possible"
  when: modprobe_test.rc != 0
  changed_when: false

- name: Unload test kernel module
  ansible.builtin.command: "rmmod dummy"
  changed_when: false

- name: Check if systemd-modules-load can be used
  stat:
    path: "/etc/modules-load.d/"
  register: s

- name: Use modprobe.d for non-systemd servers
  set_fact:
    kernel_use_systemd_modules_load: false
    kernel_modules_conf_dir: "/etc/modprobe.d"
  when: not s.stat.exists

- include_tasks: blacklist-modules.yml

- include_tasks: unload-modules.yml

- include_tasks: load-modules.yml
